### ISSUE TITLE
Issue with meson build

### ISSUE THREAD

**Issue by cakarlen** [h3adshotzz/img4helper#2]
When compiling, I am getting the following error:
`meson.build:39:0: ERROR: Dependency "lzfse" not found, tried pkgconfig, cmake and framework`
I have tried install lzfse from source and from brew but no luck.

Machine info:
Mac OSX Mojave (10.14.6)

**Comment by h3adshotzz** [comment]
You must add lzfse to your PKG_CONFIG_PATH.

**Comment by h3adshotzz** [comment]
Try running this before you build `$ export PKG_CONFIG_PATH=/usr/local/opt/lzfse/lib/pkgconfig`

**Comment by cakarlen** [comment]
Tried that and still no avail. Here is my meson-log.txt.
[meson-log.txt](https://github.com/h3adshotzz/img4helper/files/3757233/meson-log.txt)

**Comment by h3adshotzz** [comment]
Huh, does it show anything if you list the contents of `/usr/local/opt/lzfse/lib/pkgconfig`?

**Comment by cakarlen** [comment]
Ah, that file doesn't exist. I do have pkg-config installed as well as lzfse. I used brew to install both

**Comment by h3adshotzz** [comment]
Try `/usr/local/Cellar/lzfse/1.0/lib/pkgconfig`

**Comment by cakarlen** [comment]
The contents in `/usr/local/Cellar/lzfse/1.0/lib` is `liblzfse.dylib`. I have no other files inside it

**Comment by h3adshotzz** [comment]
I'm closing this issue as img4helper no longer requires any dependencies.
